### ISSUE TITLE
Entry import is disregarding post/expiry date timezones

### ISSUE THREAD

**Issue by brandonkelly** [dgrigg/craft-migration-assistant#10]
These lines:

https://github.com/dgrigg/craft-migration-assistant/blob/4a9ceff667cb183b96322824df003b0374b9e81d/src/services/EntriesContent.php#L145-L146

Should be accounting for the timezone stored in the array:

```json
{"date":"2019-07-21 17:14:00.000000","timezone_type":3,"timezone":"Europe/Brussels"}
```

For example you could do this:

```php
$entry->postDate = is_null($data['postDate']) ? '' : new DateTime($data['postDate']['date'], new DateTimeZone($data['postDate']['timezone']));
$entry->expiryDate = is_null($data['expiryDate']) ? '' : new DateTime($data['expiryDate']['date'], new DateTimeZone($data['expiryDate']['timezone']));
```

I’ve also just updated `DateTimeHelper::toDateTime()` to support passing in PHP DateTime arrays like the above (craftcms/cms@ad2f39e84654550db8b69a7d39cbf88928cdd4af), so alternatively your next release could require `"craftcms/cms": "^3.2.6"` and do this instead:

```php
$entry->postDate = is_null($data['postDate']) ? '' : DateTimeHelper::toDateTime($data['postDate']);
$entry->expiryDate = is_null($data['expiryDate']) ? '' : DateTimeHelper::toDateTime($data['expiryDate']);
```

(Leave out the `['date']` subs.)

**Comment by dgrigg** [comment]
thanks @brandonkelly, issue has been resolved.
