### ISSUE TITLE
Feature Request: Include Field Id

### ISSUE THREAD

**Issue by simeon-smith** [dgrigg/craft-migration-assistant#12]
When modifying an existing field if you change the handle it appears to create a new field when the migration is run.

If you included the field ID and checked if it existed and if so modified it you could get around this.

**Comment by dgrigg** [comment]
@simeon-smith unfortunately the id values are not consistent between database hence the reliance on the handles/slug. It's not 100% perfect (as in the case of changes/deletions) but it's more reliable than the ids.
