### ISSUE TITLE
Entries not inserted in non-translatable entries field in multilingual website

### ISSUE THREAD

**Issue by timbertens** [dgrigg/craft-migration-assistant#13]
My setup
- multilingual site (3 languages)
- section that has entries that has a matrix fields that has 3 fields
---- header (translatable field)
---- text (translatable field)
---- link to a multiple another entries (non-translatable field)

the entries that can be linked are products and have of all translatable fields, including of course a multilingual slug

In the section mentioned above the field that holds the links to the other entries (products) are not filled.  The setup I have is evolving (being the translation for the products are only recently added) and before the products all had the same slug (incorrect of course but at that time the site was just single language).  In that version the slug of the linked entries were all the same for the different languages and then the migration worked fine. 

So I believe that the process is going wrong because the slug of the linked entries are different for each language as of now (and that is of course how it should be)

I hope my explanation is clear, if not let me know ! 

Versions 
Application Info

PHP version	7.3.1
OS version	Linux 4.15.0-45-generic
Database driver & version	MySQL 5.7.25
Image driver & version	GD 7.3.1
Craft edition & version	Craft Pro 3.2.10
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	1.2.3-dev
Plugins

Activity Log	1.0.1
CodeMirror	1.0.1
CP Field Inspect	1.0.6
Do It Yourself widget	2.0.1
Field Manager	2.1.0
GeoField	1.0.0
Matrix Toolbar	1.0.6
Migration Assistant	3.1.3
Redactor	2.3.3.2
SEOMate	1.1.0
Site Switcher	2.1.0
Stamp	2.1.0
Table Maker	2.0.1
Two-Factor Authentication	2.2.0
Typed link field	1.0.19
Wheel Form	2.2.3
Wordsmith	3.0.5

**Comment by timbertens** [comment]
Just a quick update. Because we were stuck at this point, we had to look for a workaround to keep the deployment proces going.  What we've done is 
- create a 'normal' migration using migration assistant for the section mentioned above (leading to no entries in the product field)
- made a copy of this migration and changed file name and matching class name
- stripped out the 2nd and 3rd language from the JSON string, so only keeping the primary language in the JSON migration definition

When running both migrations, things are how they should be.

**Comment by dgrigg** [comment]
Hi @timbertens reading over this I want to clarify a few things:
The matrix field has a block with 3 fields in the block:
- header (translatable field)
- text (translatable field)
- link to a multiple another entries (non-translatable field)

When you run a 'content migration' the values in the header and text fields are populated correctly in their respective language entry. The link field value does not populate for any of the language entries.

Is that correct?

**Comment by timbertens** [comment]
yes, exactly.  The content of the migration file is correct (referencing the correct entries, each in their own language) as far as I can tell, but on running it I end up with no entries in the third field

**Comment by dgrigg** [comment]
@timbertens do the entries that the third field is linking to exist in the destination site before the migration is run?

**Comment by timbertens** [comment]
yes, the linked entries (being products) are created first and afterward the section (there are 3 in fact) that links to those products is migrated

**Comment by dgrigg** [comment]
ok, I will dig into this one

**Comment by dgrigg** [comment]
@timbertens trying to figure this out. I setup similar fields/sections locally and everything is working correctly.

I created a single landing page section with a matrix field with one block, block has 3 fields, 2 text fields that are translatable, one entry field that can link to an entry (product entries) that is not translatable. <img width="1774" alt="Screen Shot 2019-09-02 at 11 17 45 AM" src="https://user-images.githubusercontent.com/166361/64123829-64590700-cd73-11e9-84de-977826dae300.png">

The product entries are translatable. I created multiple products in different languages. I made sure all the product entries were exported/imported before migrating the landing page. After that I can select any product on the landing page, create a migration and then run in the destination site and everything is correct.

**Comment by timbertens** [comment]
Do your products have a different slug per product per language?

**Comment by dgrigg** [comment]
no, the products have the same slug

**Comment by timbertens** [comment]
Make them different and you should start having the issue too

**Comment by dgrigg** [comment]
Still working correctly. Can you send me a copy of the migration that was causing the issue.

**Comment by timbertens** [comment]
in your mailbox !

**Comment by dgrigg** [comment]
release version 3.1.4 should resolve this issue.

**Comment by timbertens** [comment]
yes, it does! many thanks
