### ISSUE TITLE
Categories::getGroupByHandle() must be of the type string, array given

### ISSUE THREAD

**Issue by ricricucit** [dgrigg/craft-migration-assistant#14]
### I get this:
```
An error occurred while executing the "craft\contentmigrations\m190916_213806_migration_all_fields migration: Argument 1 passed to craft\services\Categories::getGroupByHandle() must be of the type string, array given, called in /data/craft/vendor/dgrigg/craft-migration-assistant/src/services/Fields.php on line 690
```

### Doing this (AKA how to reproduce it):
1. export all fields, sections, categories, etc. on one environment
2. run that generated migration called "everything" on new, or same exact environment

**Comment by dgrigg** [comment]
@ricricucit are you getting this error if you break up the migrations to make sure the category has been migrated before a field that use the category?

**Comment by ricricucit** [comment]
didn't re-try this one, thanks for the advice. Will report back here.

**Comment by ricricucit** [comment]
Ok, @dgrigg just tried following the order you suggest in the README and broken down the migrations. I still get:

```
An error occurred while executing the "craft\contentmigrations\m190918_152054_migration_fields migration: Argument 1 passed to craft\services\Categories::getGroupByHandle() must be of the type string, array given, called in /data/craft/vendor/dgrigg/craft-migration-assistant/src/services/Fields.php on line 690
```

**Comment by ricricucit** [comment]
Do you have good hints on what could be going wrong? Also: the message says `Check the logs for details.` ...but I don't understand them :P :

```
2019-09-18 15:36:11 [-][1][-][warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
```

**Comment by dgrigg** [comment]
@ricricucit can you attach a copy of the migration file?

**Comment by ricricucit** [comment]
[m190918_152054_migration_fields.php.zip](https://github.com/dgrigg/craft-migration-assistant/files/3626770/m190918_152054_migration_fields.php.zip)

**Comment by dgrigg** [comment]
two questions: 
1. which version of migration manager are you running?
2. does the 'publicationsCategories' exist on the destination site before running the migration?

**Comment by ricricucit** [comment]
1. latest (`v3.1.4`)
2. yes

**Comment by dgrigg** [comment]
Ok, I will find a solution.

**Comment by dgrigg** [comment]
@ricricucit try to create three separate migrations in this order:
1. the category
2. the field that references the category
3. the section(s) that reference the category field

That should fix the issue.

**Comment by ricricucit** [comment]
For all those landing here from a search and for @dgrigg: 

I've _now_ realised that I forgot to delete 1 field pointing to a previously deleted category.
This was throwing the error.
