### ISSUE TITLE
Entry is missing its type ID

### ISSUE THREAD

**Issue by ricricucit** [dgrigg/craft-migration-assistant#15]
This happens when trying to migrate "Single" entries: "**Entry is missing its type ID**".

**Comment by ricricucit** [comment]
it was me. I forgot to make a migration for the section, before exporting the entry.
Thanks for this:

```
A good rule to follow for migration dependency order is:
1. Sites/locales
2. Sections
3. Asset Volumes
4. Categories
5. Fields
```

**Comment by dgrigg** [comment]
@ricricucit yes, order of operations is a must for migrations
