### ISSUE TITLE
Migration for Matrix rows is broken

### ISSUE THREAD

**Issue by bransinanderson** [dgrigg/craft-migration-assistant#18]
Craft CMS v3.3.11
Migration Assistant v3.1.5

To replicate

1. Staging create A-F rows with the Matrix field
2. Staging create entry migration where the A-F rows reside
3.  Run on production. Both entries in the two separate environments are identical

![Screenshot from 2019-12-05 13-56-37](https://user-images.githubusercontent.com/431930/70278867-ef2e1100-1769-11ea-95f7-ce7af695a976.png)

4. On staging create new Z row
5. Position Z row in the middle of the Matrix array

![Screenshot from 2019-12-05 13-57-15](https://user-images.githubusercontent.com/431930/70278974-3caa7e00-176a-11ea-8065-4a315cf92eda.png)

6. Create migration on staging
7. Run new migration on production

**Notice how the years are no longer accurate for A, C, D, E, Z and the order is no longer correct.** 

![Screenshot from 2019-12-05 14-09-09](https://user-images.githubusercontent.com/431930/70279040-66fc3b80-176a-11ea-9d4d-7434c4e8e70c.png)

**Comment by dgrigg** [comment]
@bransinanderson give release 3.1.6 a try, sort order have been fixed.
