### ISSUE TITLE
Issue creating new migration for entries 

### ISSUE THREAD

**Issue by AnthonyFerraro007** [dgrigg/craft-migration-assistant#21]
Craft Version: 3.4.0
Migration Assistant Version: 3.1 
PHP: 7.0 

 Issue occurs when trying to create a migration for page entries inside a structure section. When trying to run the migration for the entries theres no response on the page and the server returns a 500 (Internal Server Error) from the server.

**Comment by dgrigg** [comment]
Hey @AnthonyFerraro007 can you provide some details from your log file to help me pinpoint the issue.

**Comment by jbogendoerfer** [comment]
I think I have a similar problem.
Craft Pro 3.4.23
Migration Assistant | 3.1.8
PHP version | 7.3.11

When selecting a Singles Enrty (for example Homepage) and click on "create Migration" the link
http://....de/index.php?p=admin/actions/element-indexes/perform-action&v=1592324332740
creates a 500 error and returns
{"error":"Call to a member function className() on null"}

**Comment by dgrigg** [comment]
Hi, can you provide any additional details from your log file?

**Comment by jbogendoerfer** [comment]
Hi Derrick,

I attached the part of the log for the error when trying to create a
migration for a Single-Section.

Kind regards
Jürgen


Am Di., 16. Juni 2020 um 18:59 Uhr schrieb Derrick Grigg <
notifications@github.com>:

**Comment by dgrigg** [comment]
@jbogendoerfer can you email the file, github doesn't appear to be liking the attachment derrick at dgrigg dot com
