### ISSUE TITLE
Multisite-Content-Miagration imports wrong

### ISSUE THREAD

**Issue by jbogendoerfer** [dgrigg/craft-migration-assistant#23]
Craft Pro 3.4.23
Migration Assistant | 3.1.8
PHP version | 7.3.11

i have the JSON below in the migration-file,
when importing the migration the content of the field "elements" for "en" is in both sites ("de","en").
title, slug and seo get imported the right way, the german content of elements is not imported into "de".

{"content":{"entries":[{"slug":"impressum","section":"contentPage","sites":{"de":{"slug":"impressum","section":"contentPage","enabled":"1","site":"de","enabledForSite":true,"postDate":{"date":"2020-06-16 06:19:00.000000","timezone_type":3,"timezone":"America/Los_Angeles"},"expiryDate":null,"title":"Impressum","entryType":"contentPage","uid":"40dde3cf-2af0-4c4c-afef-322c04e7ce37","author":"jbogendoerfer","fields":{"elements":{"new1":{"type":"article","enabled":"1","modified":"1","collapsed":false,"level":"1","fields":{"articleLayout":"smallImageLeft","media":{"new1":{"type":"2","fields":{"desktopMedia":[{"elementType":"craft\\elements\\Asset","filename":"touchgrey.png","folder":"CMSImages","source":"cmsimages","path":""}],"mobileMedia":[],"youtubeVideoId":null}}},"headline":{"new1":{"type":"3","fields":{"text":"<p>Impressum</p>","htype":"h2"}}},"text":"<ol><li>eins</li><li>zwei</li><li>drei</li></ol><table><tbody><tr><td>a</td><td>b</td><td>c</td></tr><tr><td>d</td><td>e</td><td>f</td></tr></tbody></table><p>ENDE</p>","articleTag":null}}},"showInMenuTree":true,"seo":{"titleRaw":{"1":"Impressum"},"descriptionRaw":"Das Impressum von Inuvai","keywords":[{"keyword":"impressum","rating":"poor"},{"keyword":"inuvai","rating":"neutral"},{"keyword":"rechtliches","rating":"neutral"}],"score":"neutral","social":{"twitter":{"handle":"","title":"INUVAI - A Fresenius Company Impressum","imageId":"","description":"Das Impressum von Inuvai"},"facebook":{"handle":"","title":"INUVAI - A Fresenius Company Impressum","imageId":"","description":"Das Impressum von Inuvai"}},"advanced":{"robots":[],"canonical":""}},"pageLayout":"productPage"}},"en":{"slug":"imprint","section":"contentPage","enabled":"1","site":"en","enabledForSite":true,"postDate":{"date":"2020-06-16 06:19:00.000000","timezone_type":3,"timezone":"America/Los_Angeles"},"expiryDate":null,"title":"Imprint","entryType":"contentPage","uid":"40dde3cf-2af0-4c4c-afef-322c04e7ce37","author":"jbogendoerfer","fields":{"elements":{"new1":{"type":"article","enabled":"1","modified":"1","collapsed":false,"level":"1","fields":{"articleLayout":"smallImageLeft","media":{"new1":{"type":"2","fields":{"desktopMedia":[{"elementType":"craft\\elements\\Asset","filename":"touchgrey.png","folder":"CMSImages","source":"cmsimages","path":""}],"mobileMedia":[],"youtubeVideoId":null}}},"headline":{"new1":{"type":"3","fields":{"text":"<p>Imprint</p>","htype":"h2"}}},"text":"<ol><li>one</li><li>two</li><li>three</li></ol><table><tbody><tr><td>aa</td><td>ba</td><td>ca</td></tr><tr><td>da</td><td>ea</td><td>fa</td></tr></tbody></table><p>THE END</p>","articleTag":null}}},"showInMenuTree":true,"seo":{"titleRaw":{"1":"Impressum"},"descriptionRaw":"The Imprint for Inuvai","keywords":[{"keyword":"inuvai","rating":"neutral"},{"keyword":"legal","rating":"neutral"},{"keyword":"imprint","rating":"neutral"}],"score":"neutral","social":{"twitter":{"handle":"","title":"INUVAI - A Fresenius Company Imprint","imageId":"","description":"The Imprint for Inuvai"},"facebook":{"handle":"","title":"INUVAI - A Fresenius Company Imprint","imageId":"","description":"The Imprint for Inuvai"}},"advanced":{"robots":[],"canonical":""}},"pageLayout":"productPage"}}}}]}}

**Comment by dgrigg** [comment]
Can you attach your migration file as an attachment? 

FYI, when you run a content migration it follows the locale/site propagation rules defined on the site and field (ie matrix, supertable). What propagation settings do you have in place on the destination site?

**Comment by jbogendoerfer** [comment]
Hi Drerrick, thank you for your reply.

The Section is setup with "Save entries to all sites enabled for this
section"
Attached is the migration-file.
"DE" is my primary site.
If I create the migration-file when viewing the "EN"-Site, the only thing
that changes in the migration-file ist the first slug outside the sites
from "impressum" to "imprint".

Kind regards
Jürgen


Am Di., 16. Juni 2020 um 18:58 Uhr schrieb Derrick Grigg <
notifications@github.com>:

**Comment by dgrigg** [comment]
@jbogendoerfer can you email the file, github doesn't appear to be liking the attachment derrick at dgrigg dot com
