### ISSUE TITLE
Migration of content activates all locales in multisite setup

### ISSUE THREAD

**Issue by aselness** [dgrigg/craft-migration-assistant#24]
I currently have a multisite craft instance with multiple languages (locales). I have been trying to migrate content/entries that are active for only one language/locale, but when I run the migration from staging to production it automatically activates all locales rather than just the one specified on the staging server.

Here are my steps to create the issue:

- select page to create migration on staging server (page only active for en_us locale)
- move that migration file via SFTP from staging to production server
- run migration in craft admin on production server
- migration is successful, but when I look at the active locales, ALL locales are selected, not just en_us

Thanks for any assistance in this.

**Comment by dgrigg** [comment]
Hi @aselness are you running the latest version of Migration Assistant?

**Comment by aselness** [comment]
I'm running 3.1.6

**Comment by dgrigg** [comment]
@aselness update to 3.1.8 and you should be good https://github.com/dgrigg/craft-migration-assistant/blob/master/src/services/EntriesContent.php#L48

**Comment by aselness** [comment]
Ok great - I'll give that a shot. Thanks!
