### ISSUE TITLE
Assets no longer being applied during migration

### ISSUE THREAD

**Issue by vandyks** [dgrigg/craft-migration-assistant#25]
I noticed when importing a migration file my assets are not being applied to the entry. I noticed that the getAssetByHandle function in MigrationManagerHelper was failing to find the correct folder ID. This worked before as assets were correctly being attached but since updating to 3.1.8, it stopped working. It looks like the code was updated in that function since 3.1.6 causing the path value to be used in the folder criteria versus the name which was working before. 

Below is the data getting passed into the function. All asset lookups for this folder was returning the ID of 318 when it should have been 1 based on the data in my database. I believe it's an issue with craft trying to query on an empty path value. If I test with a path that's not empty, it finds the correct folder.

`{"elementType":"craft\\elements\\Asset","filename":"test-image.jpg","folder":"s3-assets","source":"s3Assets","path":""}`

This is the line that's returning the incorrect folder ID:

`$folder = Craft::$app->assets->findFolder($folderCriteria);`

I've solved the problem by checking that the path is not empty which is working for me for the time being.

**Comment by aryehischechter** [comment]
@vandyks I'm running into the same issue.
Can you please elaborate on how you dealt with this?

**Comment by vandyks** [comment]
@aryehischechter I had to modify the plugin code. On line 87 in vendor/dgrigg/craft-migration-assistant/src/helpers/MigrationManagerHelper.php, I changed it to this: 

`if (array_key_exists('path', $element) && !empty($element['path']))`

**Comment by dgrigg** [comment]
@vandyks @aryehischechter working on some updates for Craft 3.5 and will be adding this fix in.

**Comment by strandofgenius** [comment]
Is this fix meant to work with the Pixel & Tonic Amazons S3 plugin?
I'm running Craft 3.5.11.1 and Craft Migration Assistant 3.2.1 and it isn't including the assets when migrating an entry.
```
{"elementType":"craft\\elements\\Asset","filename":"certifications_200803_163641_1.jpg","folder":"Images","source":"images","path":""}
```

**Comment by dgrigg** [comment]
@strandofgenius It should be working. Are you using the same S3 bucket between the source and destination sites?

**Comment by strandofgenius** [comment]
I can't always see what I've uploaded from one environment to another, but local, staging and live, should all be using the same asset domain and folder since those settings are all the same based on their environment variables.

**Comment by dgrigg** [comment]
Can you confirm that all three environments are using the same S3 bucket. If they are not and the environment you are running the migration on does not have that file in their S3 bucket that would explain the empty field.

**Comment by strandofgenius** [comment]
I hadn't accounted that the live site is using a cloudfront distribution. However shouldn't it work if I were to export my live db and import into a local development to create a migration? Or would I still need to update the asset domain to point to the cloudfront url?

**Comment by dgrigg** [comment]
It should work if the asset has been indexed on the destination site and the file exists in the Asset source that is being used on the destination site. When the migration runs it using the Asset source, filename and path to find the matching asset in the destination system. If the asset can not be found you end up with an empty Asset field. That is the most typical reason for what you are seeing happen. Doing some testing here to make sure S3 buckets are working correctly, everything so far is correct.
