### ISSUE TITLE
Add ability to export tags

### ISSUE THREAD

**Issue by seanjermey** [dgrigg/craft-migration-assistant#3]
Currently you can export the tag groups but not the tags themselves

**Comment by ClemensSchneider** [comment]
This is especially annoying because the contents of tag-fields are not included when creating a content-migration, so this information is lost.

**Comment by dgrigg** [comment]
Unfortunately there's not a way in the Craft UI to see the tag content to allow any type of export. It also looks like Tags are going away in the upcoming release of Craft.
