### ISSUE TITLE
Entry type of same name as section name is created during migration

### ISSUE THREAD

**Issue by wallacio** [dgrigg/craft-migration-assistant#30]
Craft 3.5.12
MA 3.2.1

I have a section called, for the sake of an example, "Cars". It has a handle of "cars".
This section has a single Entry Type called "Car", with a handle of "car".

I create a migration for this one section using the Migration Assistant.

When applying this migration, two Entry Types are created in the Section; "Cars" and "Car". The fields associated with the "Car" entry type are correct and as expected but why is the "Cars" Entry Type created? It contains a single "title" field in the layout, but it's not defined in either the source site or the migration.

Relevant JSON from the migration (field layout removed for brevity):

```
"sections": [{
	"name": "Cars",
	"handle": "cars",
	"type": "channel",
	"enableVersioning": "1",
	"propagationMethod": "all",
	"sites": {
		"default": {
			"site": "default",
			"hasUrls": true,
			"uriFormat": "cars/{slug}",
			"enabledByDefault": true,
			"template": null
		}
	},
	"entrytypes": [{
		"sectionHandle": "cars",
		"hasTitleField": "1",
		"name": "Car",
		"handle": "car",
		"requiredFields": [],
		"fieldLayouts": {
			"tabs": [{
				}]
			}]
		}
	}]
}]

```

Which produces this:

![image](https://user-images.githubusercontent.com/7721989/94896187-c909f800-0484-11eb-97a5-58ac509ef27d.png)

Why is the "Cars" entry type created and what's the solution here?
Thanks!

**Comment by rgbjay** [comment]
Also having this exact same issue. Editing the JSON to remove the duplicate in the migration files appears to have no effect either.

**Comment by dgrigg** [comment]
@wallacio @rgbjay  this is an issue with Craft wanting to create a default entry type of the same name as the section. I will try to come up with a solution to solve this.

**Comment by rgbjay** [comment]
@dgrigg Any update on this?

**Comment by dgrigg** [comment]
@rgbjay no update yet. I will try to find a solution soon.

**Comment by dgrigg** [comment]
@rgbjay @wallacio fixed in current version
