### ISSUE TITLE
'Create migration' button is visible for regular users in 'Globals'

### ISSUE THREAD

**Issue by timbertens** [dgrigg/craft-migration-assistant#31]
I never noticed it before, but one of our clients just got confused with the fact that there is a 'Create Migration' in 'Globals' for regular users.  It is shown on the same spot as the 'Save' is normally, hence the confusion.
I believe it is the intention that the functionality from 'Migration Assistant' in only visible / accessible for Admin account, not for regular users.

<img width="1344" alt="Screenshot 2020-11-25 at 12 13 12" src="https://user-images.githubusercontent.com/1016655/100220405-9d9d0a00-2f17-11eb-9d35-e6cbfd196eef.png">

Since regular users don't have access to migration, an error ('User is not permitted to perform this action') is thrown (which is normal) but doubles the confusion

Using versions:
Craft Pro 3.5.15.1
Migration Assistant 3.2.3

**Comment by dgrigg** [comment]
@timbertens good catch. That should only be visible for users who have 'createContentMigrations' permission, same case as with the Entries/Categories etc.

**Comment by timbertens** [comment]
@dgrigg do you think it can be solved easily? I'm preparing a new release for these websites and would like to know if I can include it

**Comment by dgrigg** [comment]
@timbertens sorry been busy on a few things. I can make that update tomorrow.

**Comment by timbertens** [comment]
@dgrigg no problem, we are all over occupied .. ! Would be perfect, will plan the release this weekend in this case!

**Comment by dgrigg** [comment]
@timbertens  release 3.2.4 is available with the update.
