### ISSUE TITLE
Migration fails when grandchildren have same parent slugs

### ISSUE THREAD

**Issue by Yofamb** [dgrigg/craft-migration-assistant#32]
Not sure how to explain this, but given the following screenshot. If I create a migration of all the entries (from the dropdown, delete the entries, then run the migration I receive an error. From what I can see it is because both grand children have their parent set to 'child'. Can an id or uri be used instead? something like `"parent":"parent-2/child"` for grandchild 2?

Do you have recommendations?

<img width="1258" alt="Screen Shot 2020-12-15 at 8 10 10 pm" src="https://user-images.githubusercontent.com/3781418/102195303-8350bd80-3f12-11eb-8d65-18be5eb91cff.png">

`Exception: There was a problem getting the parent element. (/websites/thesite/vendor/craftcms/cms/src/services/Structures.php:242)`

**Comment by Yofamb** [comment]
I'm trying to migrate from an old cms to craftcms and am hoping that migration assistant can do the navigation migration. Unfortunately, there are lots of slugs that are the same :(

**Comment by dgrigg** [comment]
@Yofamb the duplicated slug could cause issues but I would expect the relationship to just end up being to the wrong parent. It might be that the parent entry does not exist when the child/grand child is getting added. You could try to do a migration first of the top level parent, then one of the child and then a final one of the grand child. Then run all 3 on the destination site.

**Comment by Yofamb** [comment]
Thanks, ill give that a go, that makes sense.
