### ISSUE TITLE
Environment variables and aliases are parsed instead of copied to migration

### ISSUE THREAD

**Issue by roelvanhintum** [dgrigg/craft-migration-assistant#33]
This like `@var` and `$VAR` are more common, and even advised, now in craft cms settings. This is useful for multi environment websites. These are now parsed, so the actual migration file doesn't contain `@var` and `$VAR` but their values instead, which is not useful. This is reproducable on the site's `siteUrl`.

**Comment by dgrigg** [comment]
I will look into this. Craft must have changed when they are parsing those values which would affect how the migration gets the data.

**Comment by dgrigg** [comment]
@roelvanhintum which version of Craft are you running? I tested on Craft 3.6.3 and everything was migrated correctly. Also, where are you putting the @var $VAR values (Assets, Sections) when they are getting parsed?

**Comment by dgrigg** [comment]
@roelvanhintum did some digging, this appears to have only been an issue in the Site settings. Fixed the name and base url values to not parse the env variables.
