### ISSUE TITLE
Exception: Undefined index: maxSiblingBlocks when migrating Neo fields

### ISSUE THREAD

**Issue by kayqq** [dgrigg/craft-migration-assistant#34]
My field migrations for Neo blocks are not including the `maxSiblingBlocks` property in the JSON settings object of the migration.

Currently my workaround is adding `"maxSiblingBlocks": "0",` to any objects with `"maxChildBlocks"` to the migration after generating it.

"craftcms/cms": "3.5.17.1",
"spicyweb/craft-neo": "2.8.16",
"dgrigg/craft-migration-assistant": "3.2.4",

Update: My workaround works but I also encountered a new issue, Neo blocks are not migrating the attached fields.

**Comment by dgrigg** [comment]
@kayqq fixed in latest version
