### ISSUE TITLE
Neo field migration is erasing all field layouts for every block

### ISSUE THREAD

**Issue by kayqq** [dgrigg/craft-migration-assistant#35]
Every time I try to run a migration for a Neo field, the attached fields for the layout and tabs all get erased. The migration runs without any errors though. This only started happening since I upgraded Neo. I think there might be some sort of mismatch of ID's maybe?

"craftcms/cms": "3.5.17.1",
"spicyweb/craft-neo": "2.8.19",
"dgrigg/craft-migration-assistant": "3.2.5",

**Comment by dgrigg** [comment]
When you say erased do you means the fields are removed from the Neo blocks?

**Comment by kayqq** [comment]
@dgrigg yes thats exactly what I mean, thanks for clarifying

**Comment by alnassif** [comment]
Hi @dgrigg has this been fixed or is there a workaround

**Comment by dgrigg** [comment]
@alnassif working on a solution, stay tuned

**Comment by dgrigg** [comment]
@kayqq @alnassif the issue have been resolved in 3.2.6  Thank you for your patience.
