### ISSUE TITLE
LinkField fields are no longer migrated correctly

### ISSUE THREAD

**Issue by timbertens** [dgrigg/craft-migration-assistant#37]
The import of LinkField migration is no longer working correctly, not sure since what version exactly but in the previous versions it definitely worked as expected.  This is the json string that is created upon creating a migration 

`    private $json = <<<'JSON'
{"content":{"entries":[{"slug":"test","section":"nieuwsItems","sites":{"default":{"slug":"test","section":"nieuwsItems","enabled":true,"site":"default","enabledForSite":true,"postDate":{"date":"2021-05-05 09:45:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"Test","entryType":"nieuws","uid":"389d6d37-6c91-43da-8862-5d99a094d5d9","author":"admin","fields":{"nieuwsIcoon":[],"introTekst":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.","contentBuilder":{"new1":{"type":"tekst","enabled":true,"sortOrder":"1","fields":{"tekst":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui. Maecenas faucibus mollis interdum.</p>"}},"new2":{"type":"ctaButton","enabled":true,"sortOrder":"2","fields":{"button":{"ariaLabel":null,"customQuery":null,"customText":"","target":"","title":null,"type":"entry","value":[{"elementType":"craft\\elements\\Entry","slug":"contacteer","section":"contact","site":"default"}],"elementType":"typedlinkfield\\fields\\LinkField"}}}},"keywords":null,"metaDescription":null,"seoImage":[],"importId":null}},"kbcAgentFrans":{"slug":"test","section":"nieuwsItems","enabled":true,"site":"kbcAgentFrans","enabledForSite":true,"postDate":{"date":"2021-05-05 09:45:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"Test","entryType":"nieuws","uid":"389d6d37-6c91-43da-8862-5d99a094d5d9","author":"admin","fields":{"nieuwsIcoon":[],"introTekst":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.","contentBuilder":{"new1":{"type":"tekst","enabled":true,"sortOrder":"1","fields":{"tekst":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui. Maecenas faucibus mollis interdum.</p>"}},"new2":{"type":"ctaButton","enabled":true,"sortOrder":"2","fields":{"button":{"ariaLabel":null,"customQuery":null,"customText":"","target":"","title":null,"type":"entry","value":[{"elementType":"craft\\elements\\Entry","slug":"contacteer","section":"contact","site":"default"}],"elementType":"typedlinkfield\\fields\\LinkField"}}}},"keywords":null,"metaDescription":null,"seoImage":[],"importId":null}},"kbcAgentEngels":{"slug":"test","section":"nieuwsItems","enabled":true,"site":"kbcAgentEngels","enabledForSite":true,"postDate":{"date":"2021-05-05 09:45:00.000000","timezone_type":3,"timezone":"Europe/Brussels"},"expiryDate":null,"title":"Test","entryType":"nieuws","uid":"389d6d37-6c91-43da-8862-5d99a094d5d9","author":"admin","fields":{"nieuwsIcoon":[],"introTekst":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.","contentBuilder":{"new1":{"type":"tekst","enabled":true,"sortOrder":"1","fields":{"tekst":"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Donec ullamcorper nulla non metus auctor fringilla. Donec sed odio dui. Maecenas faucibus mollis interdum.</p>"}},"new2":{"type":"ctaButton","enabled":true,"sortOrder":"2","fields":{"button":{"ariaLabel":null,"customQuery":null,"customText":"","target":"","title":null,"type":"entry","value":[{"elementType":"craft\\elements\\Entry","slug":"contacteer","section":"contact","site":"default"}],"elementType":"typedlinkfield\\fields\\LinkField"}}}},"keywords":null,"metaDescription":null,"seoImage":[],"importId":null}}}}]}}
JSON;`

When you look at the specific part of the LinkField, all info looks correct and complete

`"new2":{"type":"ctaButton","enabled":true,"sortOrder":"2","fields":{"button":{"ariaLabel":null,"customQuery":null,"customText":"","target":"","title":null,"type":"entry","value":[{"elementType":"craft\\elements\\Entry","slug":"contacteer","section":"contact","site":"default"}],"elementType":"typedlinkfield\\fields\\LinkField"}}}}`

As you can see in this example, the LinkField is supposed to link to the section 'contact'
However, upon running this migration, the LinkField is not populated with that entry, but left blank

<img width="614" alt="Screenshot 2021-05-05 at 10 02 39" src="https://user-images.githubusercontent.com/1016655/117112246-120e8b80-ad89-11eb-805a-49a12d039978.png">

The LinkField is part of a matrix field called 'ContentBuilder'

**Comment by dgrigg** [comment]
Are you using the latest version of Craft and Migration Assistant? Also, please confirm that the entry  with slug 'contacteer' in section 'contact' exists. Tested locally in Matrix blocks with Entry links and it is working correctly.

**Comment by timbertens** [comment]
yes, using 

- Craft Pro 3.6.13
- Migration Assistant 3.2.6

yes, see screenshot.  Don't know if that would make difference, but it is a 'Single'

<img width="1043" alt="Screenshot 2021-05-05 at 17 10 33" src="https://user-images.githubusercontent.com/1016655/117164321-ced20e00-adc4-11eb-90ba-66e3b95f3ae6.png">

<img width="1043" alt="Screenshot 2021-05-05 at 17 11 22" src="https://user-images.githubusercontent.com/1016655/117164448-eb6e4600-adc4-11eb-805e-28b324f93139.png">

**Comment by dgrigg** [comment]
Tested with asset, single entry and section entry locally, all worked correctly. On the destination site the 'contact' entry exists and is enabled for the 'default' site?

**Comment by timbertens** [comment]
First of all, thanks for the search. Looking further into this, I can see a non-intended difference 

**source site**
<img width="1070" alt="Screenshot 2021-05-06 at 10 23 14" src="https://user-images.githubusercontent.com/1016655/117266080-2c15a000-ae55-11eb-8bb9-2515b82fe234.png">

**destination site**
<img width="1069" alt="Screenshot 2021-05-06 at 10 23 24" src="https://user-images.githubusercontent.com/1016655/117266090-2e77fa00-ae55-11eb-9715-67e215c5b68a.png">


It appears that in https://github.com/craftcms/cms/issues/3368 the option was added to CraftCMS 3.2 to specify a slug on a single, this did not exist before and the slugs for singles were always the same in both source and destination sites.  

Even stranger is that as far as I can see, this added functionality does not actually have an effect on the slug used, the one set in the section config still applies, but I guess this is what makes MigrationAssistant fail to insert the 'Contact' page in that LinkField as the slugs are used as key and they are different.

**Comment by dgrigg** [comment]
Ah, yes I do recall we had to make a slight tweak because of that change in Craft to make sure we got the entry slug on singles. Glad you sorted it out.
