### ISSUE TITLE
Migrating between environments

### ISSUE THREAD

**Issue by drewkennelly** [dgrigg/craft-migration-assistant#39]
Hi,

We are using the plugin and it works great when we make changes locally, commit the migrations and deploy.

One thing we are stuck with though is once the site is deployed and a user creates some new content and creates a migration, how do we download the migration files without having to SSH to the server and download them? We need a process that works for non-technical users.

Also, because we are in a multi-server load balanced setup, the generated migration files would only exist on the server the user was on when they ran the migration. Is it possible to use AWS S3 for storing the migration files instead?

Thanks,
Drew

**Comment by dgrigg** [comment]
Hi Drew, unfortunately the migrations need to be within the 'migrations' folder which is dictated by Craft (and Yii). I could investigate adding some type of event to dispatch after a migration has been created that could be listened for and dealt with (ie use a custom module to hear about the new migration and do something with the file).
