### ISSUE TITLE
Craft 2 migration to run on Craft 3

### ISSUE THREAD

**Issue by kevadamson** [dgrigg/craft-migration-assistant#41]
I have a website my client has needed to keep using while I update them to Craft 3, and I'd now like to migrate some of the changes they have made during this time over to the Craft 3. Creating the migration file in Craft 2 and then simply trying to run it in the new plugin in Craft 3 generates an error. Is there a simple conversion I can do to the migration file to get it to work? From a test file generated in Craft 3 using the migration plugin shows that there are some obvious differences- for e.g. the `use` declarations, and also how the json is written etc.

**Comment by dgrigg** [comment]
@kevadamson unfortunately Craft 2 migrations won't work in Craft 3. The migration structure is quite different between the two. Your best option would be to make a backup of the production server, copy to that to an environment where you safely upgrade to Craft 3, add in the changes you made that are not on production yet and then move that back to production when done. Replace your staging copy with that new Craft 3 copy and then you are good to continue in Craft 3.
