### ISSUE TITLE
Asset fields not included in content migration

### ISSUE THREAD

**Issue by membla** [dgrigg/craft-migration-assistant#42]
When doing a content migration, we've discovered that while the mapping to related assets are migrated fine as long as the assets are indexed before the migration is run but any field data related to the asset is not. This unfortunately makes the solution unviable for us. Is this an unsupported feature, a bug, or something we potentially could work around?

**Comment by dgrigg** [comment]
Unfortunately we don't have content migrations for the related field data on assets. It is something we could look at adding, to be honest it has never been requested.

**Comment by membla** [comment]
> Unfortunately we don't have content migrations for the related field data on assets. It is something we could look at adding, to be honest it has never been requested.

I think full support for all content – at least for core Craft fields – would be welcome for anyone doing content migrations. So that would include tags too.
