### ISSUE TITLE
Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed

### ISSUE THREAD

**Issue by tprice-macsales** [dgrigg/craft-migration-assistant#43]
We're trying to run a migration inside craftcms installed on a docker, and get this error.

`An error occurred while executing the "craft\contentmigrations\m220222_112404_migration_tprice migration: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed
Check the logs for details.`

We're running:

Craft 3.7.30.1
Neo 2.12.3
Migration Assistant 3.2.7

**Comment by dgrigg** [comment]
Did you install PHP in Docker with iconv?

**Comment by dgrigg** [comment]
closing, no reply
