### ISSUE TITLE
Can't migrate the categories, There was a problem getting the parent element.

### ISSUE THREAD

**Issue by metheeruetaichetcharoen-toast** [dgrigg/craft-migration-assistant#46]
I kept getting an error "There was a problem getting the parent element." when I tried to migrate the categories from the regional site. I have ensure that there is a parent element, I did even tried to migrate only the parent level first but still didn't seem to work as expected.

**Comment by metheeruetaichetcharoen-toast** [comment]
I did tried both scenarios, migrated the parent category first or migrate them all together. It wasn't working. Was it because I have multiple sites?

**Comment by dgrigg** [comment]
It could be a site issue and not able to find the correct parent based on the site. Unfortunately with nested content and relationships the content migrations can be problematic.
