### ISSUE TITLE
Unknown method: craft\web\Application::getAssetTransforms()

### ISSUE THREAD

**Issue by andyra** [dgrigg/craft-migration-assistant#48]
I'm using Craft 4.1.1 and just installed the trial of Migration Assistant. I clicked on the Migration Assistant item in the sidebar and was greeted with this error:

```
Twig Runtime Error – [Twig\Error\RuntimeError](http://twig.sensiolabs.org/api/2.x/Twig/Error/RuntimeError.html)
Calling unknown method: craft\web\Application::getAssetTransforms()
```

Let me know if there are other details I can provide!

**Comment by andyra** [comment]
I'm assuming this works for Craft 4—it says as much in the Craft plugin store, but these docs mention v3 quite a bit.

**Comment by dgrigg** [comment]
Hi @andyra. We have not upgraded the plugin to support Craft 4 yet. I'm not sure why the plugin store is showing otherwise.

**Comment by andyra** [comment]
Gotcha, thanks for the update! Do you have plans to update to v4 in the near future?

**Comment by dgrigg** [comment]
Undetermined at this point. Since mid Craft 3 the project config has effectively replaced the use case for the bulk of what the plugin does. With Craft 4 project config can't be disabled (to the best of my knowledge).

**Comment by jacksutherland** [comment]
Craft needs to get this out of the Craft 4 plugin store. I've installed it twice now (forgot about the first time), wasting time debugging it before it's even updated.
