### ISSUE TITLE
CraftCMS 4 support

### ISSUE THREAD

**Issue by alexkuzmin** [dgrigg/craft-migration-assistant#50]
Does the plugin support CraftCMS 4? Here is written it does https://plugins.craftcms.com/migrationassistant , it installs on 4.3.6 through Control Panel, but throws immediately the error `Calling unknown method: craft\web\Application::getAssetTransforms()`. I've removed calling of that method, and the plugin starts to show it's homepage, but after trying to make a migration for section it throws another error: `Calling unknown method: craft\models\FieldLayoutTab::getFields()`.

**Comment by dgrigg** [comment]
@alexkuzmin unfortunately it does not support Craft 4. I considered the updates and support for it but with project config being the standard now for Craft settings it doesn't really have a strong use case.

**Comment by arnedem** [comment]
@dgrigg what about content migrations?

**Comment by dgrigg** [comment]
@arnedem https://docs.craftcms.com/feed-me/v4/ is your best bet. I have used it on multiple projects, solid plugin.

**Comment by dgrigg** [comment]
Closing this
