### ISSUE TITLE
Default user group by UID

### ISSUE THREAD

**Issue by tim-thaler** [dgrigg/craft-migration-assistant#7]
Hey guys,
if I select a default user group under settings->user settings there is an error with exporting user groups. The system user settings returns now a uid for the default group but the function call is done with getGroupById()

Craft Version 3.1.26

src/services/UserGroups.php: 60 - OLD
` if ($newGroup['settings']['defaultGroup'] != null) {
                $group = Craft::$app->userGroups->getGroupById($newGroup['settings']['defaultGroup']);
                $newGroup['settings']['defaultGroup'] = $group->handle;
            }`

NEEDS TO BE
` if ($newGroup['settings']['defaultGroup'] != null) {
                $group = Craft::$app->userGroups->getGroupByUid($newGroup['settings']['defaultGroup']);
                $newGroup['settings']['defaultGroup'] = $group->handle;
            }`

**Comment by dgrigg** [comment]
fixed in latest release
