### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uid' cannot be null

### ISSUE THREAD

**Issue by jonXmack** [dgrigg/craft-migration-assistant#8]
I'm having an issue running a migration on a site I'm working on. It has multiple sites and I'm trying to get the content from one specific sites home page entry. I've edited the json in the migration file so it's limited to the one entry, but every time I try to run it I get the following error:

```
An error occurred while executing the "craft\contentmigrations\m190528_121407_migration_entry_home migration: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uid' cannot be null The SQL being executed was: UPDATE `craft_elements` SET `fieldLayoutId`=1440, `enabled`=1, `archived`=0, `dateUpdated`='2019-05-28 12:49:14', `uid`=NULL WHERE `id`=2254
```

Any pointers or advice on what I'm doing wrong or suggestions on how to fix it would be great, thanks.

**Comment by dgrigg** [comment]
Hi Jon, what type of migration are you trying to create? Field, section, content and are you using the latest version of Migration Assistant?

**Comment by jonXmack** [comment]
Hi, I'm exporting an entry, using the latest version of Migration Assistant and Craft

**Comment by dgrigg** [comment]
fixed in latest release
